name: GHDL Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install GHDL
        run: |
          sudo apt-get update
          sudo apt-get install -y ghdl
      - name: Run simulation
        run: |
          ghdl -a --std=08 -Wall src/processor.vhd sim/testbench.vhd
          ghdl -e --std=08 -Wall testbench
          ghdl -r --std=08 -Wall testbench --stop-time=6500ns --assert-level=error
